version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/nest-template
    overwrite: yes
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      runas: root
