version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/nest-template
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      runas: ubuntu
