# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NestJS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout source code.
      uses: actions/checkout@v2
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
  deploy:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - name: create env file
        working-directory: ./server
        run: |
          touch .env
          cat << EOF >> .env
          ${{ secrets.ENV }}
    
      - name: zip distributions
        run: zip -r nest-template.zip ./server/dist
        
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        working-directory: ./server
        run: aws s3 cp --region ap-northeast-2 nest-template.zip s3://suyeoniii-bucket/codedeploy

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name nest-template-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name deploy-group
          --s3-location bucket=suyeoniii-bucket,bundleType=zip,key=codedeploy/nest-template.zip
